version: 2

models:

  - name: silver_orders
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - product_id
    columns:
      - name: order_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: total_amount
        tests:
          - not_null

  - name: silver_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: silver_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
